### PR TITLE
Remove is_mobile

### PR DESCRIPTION
**Pull request by andrey-p**
This is probably good to merge as-is.

cc @bsstoner @bbraithwaite

### CODE REVIEW

**Comment by andrey-p** [comment]
:+1:

**Comment by bsstoner** [comment]
👍

**Comment by moollaza** [comment]
Just wondering, are we removing `is_mobile`? Several Spice IAs currently use it:

https://github.com/duckduckgo/zeroclickinfo-spice/search?utf8=%E2%9C%93&q=is_mobile

**Comment by andrey-p** [comment]
@moollaza Yeah, I'm doing a pass on legacy global variables. I've got a PR for both Spice and Goodies: https://github.com/duckduckgo/zeroclickinfo-spice/pull/2885, https://github.com/duckduckgo/zeroclickinfo-goodies/pull/3363

**Pull request merged**
